// <auto-generated />
using System;
using GestionFerias_CTPINVU.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionFerias_CTPINVU.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoFeria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("tipo_feria");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("CategoriaId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TipoFeria" }, "idx_cat_tipo_feria");

                    b.HasIndex(new[] { "Nombre", "TipoFeria" }, "uq_categoria_tipo")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.CentroTelefono", b =>
                {
                    b.Property<long>("CentroTelefonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("centro_telefono_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CentroTelefonoId"));

                    b.Property<long>("CentroId")
                        .HasColumnType("bigint")
                        .HasColumnName("centro_id");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_principal");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tipo");

                    b.HasKey("CentroTelefonoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CentroId", "Telefono" }, "uq_centro_tel")
                        .IsUnique();

                    b.ToTable("centro_telefonos", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.CentrosEducativo", b =>
                {
                    b.Property<long>("CentroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("centro_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CentroId"));

                    b.Property<string>("CircuitoEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("circuito_educativo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("DireccionRegional")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("direccion_regional");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("NombreCentro")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre_centro");

                    b.Property<string>("NombreDirector")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre_director");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("CentroId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CircuitoEducativo" }, "idx_centros_circuito");

                    b.HasIndex(new[] { "NombreCentro" }, "idx_centros_nombre");

                    b.ToTable("centros_educativos", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Estudiante", b =>
                {
                    b.Property<long>("EstudianteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("Grado")
                        .HasColumnType("enum('7','8','9','10','11')")
                        .HasColumnName("grado");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("EstudianteId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Grado" }, "idx_estudiantes_grado");

                    b.ToTable("estudiantes", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Evento", b =>
                {
                    b.Property<long>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("EventoId"));

                    b.Property<long>("CentroId")
                        .HasColumnType("bigint")
                        .HasColumnName("centro_id");

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo_evento");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("EstadoEvento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('En proceso','Finalizado','Cancelado')")
                        .HasColumnName("estado_evento")
                        .HasDefaultValueSql("'En proceso'");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre_evento");

                    b.Property<string>("TipoFeria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("tipo_feria");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("EventoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CodigoEvento" }, "codigo_evento")
                        .IsUnique();

                    b.HasIndex(new[] { "CentroId" }, "fk_eventos_centro");

                    b.HasIndex(new[] { "FechaInicio", "FechaFin" }, "idx_eventos_fechas");

                    b.HasIndex(new[] { "NombreEvento" }, "idx_eventos_nombre");

                    b.HasIndex(new[] { "TipoFeria" }, "idx_eventos_tipo_feria");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.InscripcionIntegrante", b =>
                {
                    b.Property<long>("InscripcionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inscripcion_id");

                    b.Property<long>("EstudianteUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("estudiante_usuario_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("InscripcionId", "EstudianteUsuarioId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "EstudianteUsuarioId" }, "fk_integ_estudiante");

                    b.ToTable("inscripcion_integrantes", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Inscripcione", b =>
                {
                    b.Property<long>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("inscripcion_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("InscripcionId"));

                    b.Property<string>("DescripcionProyecto")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_proyecto");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("EstadoInscripcion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Pendiente','Aprobado','Rechazado')")
                        .HasColumnName("estado_inscripcion")
                        .HasDefaultValueSql("'Pendiente'");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("Justificacion")
                        .HasColumnType("text")
                        .HasColumnName("justificacion");

                    b.Property<long>("LiderUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("lider_usuario_id");

                    b.Property<int>("SubcategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("subcategoria_id");

                    b.Property<string>("TituloProyecto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("titulo_proyecto");

                    b.Property<long?>("TutorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("tutor_usuario_id");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("InscripcionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EventoId" }, "fk_insc_evento");

                    b.HasIndex(new[] { "LiderUsuarioId" }, "fk_insc_lider");

                    b.HasIndex(new[] { "SubcategoriaId" }, "fk_insc_subcat");

                    b.HasIndex(new[] { "TutorUsuarioId" }, "fk_insc_tutor");

                    b.HasIndex(new[] { "TituloProyecto" }, "idx_insc_titulo");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Juece", b =>
                {
                    b.Property<long>("JuezId")
                        .HasColumnType("bigint")
                        .HasColumnName("juez_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("JuezId")
                        .HasName("PRIMARY");

                    b.ToTable("jueces", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Persona", b =>
                {
                    b.Property<long>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("persona_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PersonaId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("documento");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombres");

                    b.Property<string>("Sexo")
                        .HasColumnType("enum('Masculino','Femenino','Otro','Prefiero no decir')")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("PersonaId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Documento" }, "documento")
                        .IsUnique();

                    b.ToTable("personas", (string)null);

                    b.HasData(
                        new
                        {
                            PersonaId = 1L,
                            Apellidos = "Sistema",
                            Documento = "000000000",
                            FechaCreacion = new DateTime(2026, 4, 17, 10, 2, 1, 910, DateTimeKind.Local).AddTicks(4330),
                            Nombres = "Administrador"
                        });
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.ResultadosEvento", b =>
                {
                    b.Property<long>("ResultadoEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("resultado_evento_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ResultadoEventoId"));

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("EstadoResultados")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Pendiente','Publicado')")
                        .HasColumnName("estado_resultados")
                        .HasDefaultValueSql("'Pendiente'");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_publicacion");

                    b.Property<long?>("JuezResponsableUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("juez_responsable_usuario_id");

                    b.Property<string>("ResolucionFinal")
                        .HasColumnType("text")
                        .HasColumnName("resolucion_final");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("ResultadoEventoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EventoId" }, "evento_id");

                    b.HasIndex(new[] { "JuezResponsableUsuarioId" }, "fk_res_juez");

                    b.HasIndex(new[] { "FechaPublicacion" }, "idx_res_fecha");

                    b.ToTable("resultados_eventos", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.ResultadosGanadore", b =>
                {
                    b.Property<long>("ResultadoEventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("resultado_evento_id");

                    b.Property<sbyte>("Posicion")
                        .HasColumnType("tinyint")
                        .HasColumnName("posicion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<long>("InscripcionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inscripcion_id");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("nota");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("ResultadoEventoId", "Posicion")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "InscripcionId" }, "fk_ganadores_inscripcion");

                    b.HasIndex(new[] { "ResultadoEventoId", "InscripcionId" }, "uq_no_repetir_grupo")
                        .IsUnique();

                    b.ToTable("resultados_ganadores", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_rol");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("RolId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NombreRol" }, "nombre_rol")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Descripcion = "Administrador del sistema",
                            FechaCreacion = new DateTime(2026, 4, 17, 10, 2, 1, 910, DateTimeKind.Local).AddTicks(4180),
                            NombreRol = "Administrador"
                        });
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Subcategoria", b =>
                {
                    b.Property<int>("SubcategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subcategoria_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubcategoriaId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("SubcategoriaId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoriaId", "Nombre" }, "uq_cat_subcat")
                        .IsUnique();

                    b.ToTable("subcategorias", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Tutore", b =>
                {
                    b.Property<long>("TutorId")
                        .HasColumnType("bigint")
                        .HasColumnName("tutor_id");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("especialidad");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("TutorId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Especialidad" }, "idx_tutores_especialidad");

                    b.ToTable("tutores", (string)null);
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Usuario", b =>
                {
                    b.Property<long>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Activo','Inactivo')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Activo'");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnName("persona_id");

                    b.Property<bool>("RequiereCambioClave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_cambio_clave");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime")
                        .HasColumnName("ultimo_acceso");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("UsuarioId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Correo" }, "correo")
                        .IsUnique();

                    b.HasIndex(new[] { "UsuarioCreacion" }, "fk_usu_creacion");

                    b.HasIndex(new[] { "UsuarioModificacion" }, "fk_usu_modificacion");

                    b.HasIndex(new[] { "Estado" }, "idx_usuarios_estado");

                    b.HasIndex(new[] { "PersonaId" }, "persona_id")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1L,
                            Correo = "admin@invu.cr",
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2026, 4, 17, 10, 2, 1, 910, DateTimeKind.Local).AddTicks(4350),
                            PasswordHash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            PersonaId = 1L,
                            RequiereCambioClave = false
                        });
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.UsuarioRole", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<DateTime?>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("FechaModificacion"));

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_creacion");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "RolId" }, "fk_uroles_rol");

                    b.ToTable("usuario_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1L,
                            RolId = 1,
                            FechaAsignacion = new DateTime(2026, 4, 17, 10, 2, 1, 910, DateTimeKind.Local).AddTicks(4370),
                            FechaCreacion = new DateTime(2026, 4, 17, 10, 2, 1, 910, DateTimeKind.Local).AddTicks(4380)
                        });
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.CentroTelefono", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.CentrosEducativo", "Centro")
                        .WithMany("CentroTelefonos")
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_centro_tel_centro");

                    b.Navigation("Centro");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Estudiante", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Usuario", "EstudianteNavigation")
                        .WithOne("Estudiante")
                        .HasForeignKey("GestionFerias_CTPINVU.Models.Estudiante", "EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estudiantes_usuario");

                    b.Navigation("EstudianteNavigation");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Evento", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.CentrosEducativo", "Centro")
                        .WithMany("Eventos")
                        .HasForeignKey("CentroId")
                        .IsRequired()
                        .HasConstraintName("fk_eventos_centro");

                    b.Navigation("Centro");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.InscripcionIntegrante", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Estudiante", "EstudianteUsuario")
                        .WithMany("InscripcionIntegrantes")
                        .HasForeignKey("EstudianteUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integ_estudiante");

                    b.HasOne("GestionFerias_CTPINVU.Models.Inscripcione", "Inscripcion")
                        .WithMany("InscripcionIntegrantes")
                        .HasForeignKey("InscripcionId")
                        .IsRequired()
                        .HasConstraintName("fk_integ_inscripcion");

                    b.Navigation("EstudianteUsuario");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Inscripcione", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Evento", "Evento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoId")
                        .IsRequired()
                        .HasConstraintName("fk_insc_evento");

                    b.HasOne("GestionFerias_CTPINVU.Models.Usuario", "LiderUsuario")
                        .WithMany("Inscripciones")
                        .HasForeignKey("LiderUsuarioId")
                        .IsRequired()
                        .HasConstraintName("fk_insc_lider");

                    b.HasOne("GestionFerias_CTPINVU.Models.Subcategoria", "Subcategoria")
                        .WithMany("Inscripciones")
                        .HasForeignKey("SubcategoriaId")
                        .IsRequired()
                        .HasConstraintName("fk_insc_subcat");

                    b.HasOne("GestionFerias_CTPINVU.Models.Tutore", "TutorUsuario")
                        .WithMany("Inscripciones")
                        .HasForeignKey("TutorUsuarioId")
                        .HasConstraintName("fk_insc_tutor");

                    b.Navigation("Evento");

                    b.Navigation("LiderUsuario");

                    b.Navigation("Subcategoria");

                    b.Navigation("TutorUsuario");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Juece", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Usuario", "Juez")
                        .WithOne("Juece")
                        .HasForeignKey("GestionFerias_CTPINVU.Models.Juece", "JuezId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jueces_usuario");

                    b.Navigation("Juez");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.ResultadosEvento", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Evento", "Evento")
                        .WithMany("ResultadosEventos")
                        .HasForeignKey("EventoId")
                        .IsRequired()
                        .HasConstraintName("fk_res_evento");

                    b.HasOne("GestionFerias_CTPINVU.Models.Juece", "JuezResponsableUsuario")
                        .WithMany("ResultadosEventos")
                        .HasForeignKey("JuezResponsableUsuarioId")
                        .HasConstraintName("fk_res_juez");

                    b.Navigation("Evento");

                    b.Navigation("JuezResponsableUsuario");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.ResultadosGanadore", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Inscripcione", "Inscripcion")
                        .WithMany("ResultadosGanadores")
                        .HasForeignKey("InscripcionId")
                        .IsRequired()
                        .HasConstraintName("fk_ganadores_inscripcion");

                    b.HasOne("GestionFerias_CTPINVU.Models.ResultadosEvento", "ResultadoEvento")
                        .WithMany("ResultadosGanadores")
                        .HasForeignKey("ResultadoEventoId")
                        .IsRequired()
                        .HasConstraintName("fk_ganadores_resultado");

                    b.Navigation("Inscripcion");

                    b.Navigation("ResultadoEvento");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Subcategoria", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Categoria", "Categoria")
                        .WithMany("Subcategoria")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("fk_subcat_categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Tutore", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Usuario", "Tutor")
                        .WithOne("Tutore")
                        .HasForeignKey("GestionFerias_CTPINVU.Models.Tutore", "TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutores_usuario");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Usuario", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("GestionFerias_CTPINVU.Models.Usuario", "PersonaId")
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_persona");

                    b.HasOne("GestionFerias_CTPINVU.Models.Usuario", "UsuarioCreacionNavigation")
                        .WithMany("InverseUsuarioCreacionNavigation")
                        .HasForeignKey("UsuarioCreacion")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usu_creacion");

                    b.HasOne("GestionFerias_CTPINVU.Models.Usuario", "UsuarioModificacionNavigation")
                        .WithMany("InverseUsuarioModificacionNavigation")
                        .HasForeignKey("UsuarioModificacion")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usu_modificacion");

                    b.Navigation("Persona");

                    b.Navigation("UsuarioCreacionNavigation");

                    b.Navigation("UsuarioModificacionNavigation");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.UsuarioRole", b =>
                {
                    b.HasOne("GestionFerias_CTPINVU.Models.Role", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("fk_uroles_rol");

                    b.HasOne("GestionFerias_CTPINVU.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("fk_uroles_usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Categoria", b =>
                {
                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.CentrosEducativo", b =>
                {
                    b.Navigation("CentroTelefonos");

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Estudiante", b =>
                {
                    b.Navigation("InscripcionIntegrantes");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Evento", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("ResultadosEventos");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Inscripcione", b =>
                {
                    b.Navigation("InscripcionIntegrantes");

                    b.Navigation("ResultadosGanadores");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Juece", b =>
                {
                    b.Navigation("ResultadosEventos");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Persona", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.ResultadosEvento", b =>
                {
                    b.Navigation("ResultadosGanadores");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Role", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Subcategoria", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Tutore", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("GestionFerias_CTPINVU.Models.Usuario", b =>
                {
                    b.Navigation("Estudiante");

                    b.Navigation("Inscripciones");

                    b.Navigation("InverseUsuarioCreacionNavigation");

                    b.Navigation("InverseUsuarioModificacionNavigation");

                    b.Navigation("Juece");

                    b.Navigation("Tutore");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
